Enhance email and domain blacklist/whitelist scripts to check for file existence before updating entries, ensuring smoother execution and preventing errors when files are missing.

diff --git a/bin/v-blacklist-email-account b/bin/v-blacklist-email-account
--- a/bin/v-blacklist-email-account
+++ b/bin/v-blacklist-email-account
@@ -69,30 +69,46 @@ SPAMASSASSIN_ENTRY="blacklist_from $EMAIL"
 #                   Exim4 Blacklist                        #
 #----------------------------------------------------------#
 
-echo "Updating $DENY_SENDERS_FILE..."
-if ! check_entry_exists "$EXIM_ENTRY" "$DENY_SENDERS_FILE"; then
-    add_entry_to_file "$EXIM_ENTRY" "$DENY_SENDERS_FILE"
-    echo "Added $EXIM_ENTRY to $DENY_SENDERS_FILE."
-else
-    echo "$EXIM_ENTRY already exists in $DENY_SENDERS_FILE."
+if [ -f "$DENY_SENDERS_FILE" ]; then
+    echo "Updating $DENY_SENDERS_FILE..."
+    if ! check_entry_exists "$EXIM_ENTRY" "$DENY_SENDERS_FILE"; then
+        add_entry_to_file "$EXIM_ENTRY" "$DENY_SENDERS_FILE"
+        echo "Added $EXIM_ENTRY to $DENY_SENDERS_FILE."
+    else
+        echo "$EXIM_ENTRY already exists in $DENY_SENDERS_FILE."
+    fi
 fi
 
 #----------------------------------------------------------#
 #                SpamAssassin Blacklist                    #
 #----------------------------------------------------------#
 
-echo "Updating $SPAMASSASSIN_FILE..."
-if ! check_entry_exists "$SPAMASSASSIN_ENTRY" "$SPAMASSASSIN_FILE"; then
-    add_entry_to_file "$SPAMASSASSIN_ENTRY" "$SPAMASSASSIN_FILE"
-    echo "Added $SPAMASSASSIN_ENTRY to $SPAMASSASSIN_FILE."
-    SPAMASSASSIN_CHANGED=true
-else
-    echo "$SPAMASSASSIN_ENTRY already exists in $SPAMASSASSIN_FILE."
-fi
+if [ -f "$SPAMASSASSIN_FILE" ]; then
+    echo "Updating $SPAMASSASSIN_FILE..."
+    if ! check_entry_exists "$SPAMASSASSIN_ENTRY" "$SPAMASSASSIN_FILE"; then
+        add_entry_to_file "$SPAMASSASSIN_ENTRY" "$SPAMASSASSIN_FILE"
+        echo "Added $SPAMASSASSIN_ENTRY to $SPAMASSASSIN_FILE."
+        SPAMASSASSIN_CHANGED=true
+    else
+        echo "$SPAMASSASSIN_ENTRY already exists in $SPAMASSASSIN_FILE."
+    fi
 
-if [ "$SPAMASSASSIN_CHANGED" == "true" ]; then
-    systemctl restart "$SPAMD_SERVICE"
-    echo "SpamAssassin service ($SPAMD_SERVICE) restarted."
+    if [ "$SPAMASSASSIN_CHANGED" == "true" ]; then
+        spamassassin_running=$(/usr/local/vesta/bin/v-list-sys-services | grep 'spamassassin\|spamd' | grep -c 'running')
+        if [ $spamassassin_running -eq 1 ]; then
+            echo "== Restarting SpamAssassin"
+            systemctl restart "$SPAMD_SERVICE"
+            if [ $? -eq 0 ]; then
+                echo "SpamAssassin service ($SPAMD_SERVICE) restarted."
+            else
+                echo "Failed to restart SpamAssassin service ($SPAMD_SERVICE)."
+                exit 1
+            fi
+        else
+            echo "WARNING: SpamAssassin service ($SPAMD_SERVICE) is not running."
+            exit 1
+        fi
+    fi
 fi
 
 #----------------------------------------------------------#
diff --git a/bin/v-blacklist-email-domain b/bin/v-blacklist-email-domain
--- a/bin/v-blacklist-email-domain
+++ b/bin/v-blacklist-email-domain
@@ -81,20 +81,22 @@ SPAMASSASSIN_ENTRY_SUB="blacklist_from *.$DOMAIN"
 #                   Exim4 Blacklist                        #
 #----------------------------------------------------------#
 
-echo "Updating $DENY_SENDERS_FILE..."
-if ! check_domain_exists "$EXIM_ENTRY_MAIN" "$DENY_SENDERS_FILE"; then
-    add_domain_to_file "$EXIM_ENTRY_MAIN" "$DENY_SENDERS_FILE"
-    echo "Added $EXIM_ENTRY_MAIN to $DENY_SENDERS_FILE."
-else
-    echo "$EXIM_ENTRY_MAIN already exists in $DENY_SENDERS_FILE."
-fi
-
-if [ "$SUBDOMAIN" == "YES" ]; then
-    if ! check_domain_exists "$EXIM_ENTRY_SUB" "$DENY_SENDERS_FILE"; then
-        add_domain_to_file "$EXIM_ENTRY_SUB" "$DENY_SENDERS_FILE"
-        echo "Added $EXIM_ENTRY_SUB to $DENY_SENDERS_FILE."
+if [ -f "$DENY_SENDERS_FILE" ]; then
+    echo "Updating $DENY_SENDERS_FILE..."
+    if ! check_domain_exists "$EXIM_ENTRY_MAIN" "$DENY_SENDERS_FILE"; then
+        add_domain_to_file "$EXIM_ENTRY_MAIN" "$DENY_SENDERS_FILE"
+        echo "Added $EXIM_ENTRY_MAIN to $DENY_SENDERS_FILE."
     else
-        echo "$EXIM_ENTRY_SUB already exists in $DENY_SENDERS_FILE."
+        echo "$EXIM_ENTRY_MAIN already exists in $DENY_SENDERS_FILE."
+    fi
+
+    if [ "$SUBDOMAIN" == "YES" ]; then
+        if ! check_domain_exists "$EXIM_ENTRY_SUB" "$DENY_SENDERS_FILE"; then
+            add_domain_to_file "$EXIM_ENTRY_SUB" "$DENY_SENDERS_FILE"
+            echo "Added $EXIM_ENTRY_SUB to $DENY_SENDERS_FILE."
+        else
+            echo "$EXIM_ENTRY_SUB already exists in $DENY_SENDERS_FILE."
+        fi
     fi
 fi
 
@@ -102,28 +104,42 @@ fi
 #                SpamAssassin Blacklist                    #
 #----------------------------------------------------------#
 
-echo "Updating $SPAMASSASSIN_FILE..."
-if ! check_spamassassin_exists "$SPAMASSASSIN_ENTRY_MAIN" "$SPAMASSASSIN_FILE"; then
-    add_domain_to_file "$SPAMASSASSIN_ENTRY_MAIN" "$SPAMASSASSIN_FILE"
-    echo "Added $SPAMASSASSIN_ENTRY_MAIN to $SPAMASSASSIN_FILE."
-    SPAMASSASSIN_CHANGED=true
-else
-    echo "$SPAMASSASSIN_ENTRY_MAIN already exists in $SPAMASSASSIN_FILE."
-fi
-
-if [ "$SUBDOMAIN" == "YES" ]; then
-    if ! check_spamassassin_exists "$SPAMASSASSIN_ENTRY_SUB" "$SPAMASSASSIN_FILE"; then
-        add_domain_to_file "$SPAMASSASSIN_ENTRY_SUB" "$SPAMASSASSIN_FILE"
-        echo "Added $SPAMASSASSIN_ENTRY_SUB to $SPAMASSASSIN_FILE."
+if [ -f "$SPAMASSASSIN_FILE" ]; then
+        echo "Updating $SPAMASSASSIN_FILE..."
+    if ! check_spamassassin_exists "$SPAMASSASSIN_ENTRY_MAIN" "$SPAMASSASSIN_FILE"; then
+        add_domain_to_file "$SPAMASSASSIN_ENTRY_MAIN" "$SPAMASSASSIN_FILE"
+        echo "Added $SPAMASSASSIN_ENTRY_MAIN to $SPAMASSASSIN_FILE."
         SPAMASSASSIN_CHANGED=true
     else
-        echo "$SPAMASSASSIN_ENTRY_SUB already exists in $SPAMASSASSIN_FILE."
+        echo "$SPAMASSASSIN_ENTRY_MAIN already exists in $SPAMASSASSIN_FILE."
     fi
-fi
 
-if [ "$SPAMASSASSIN_CHANGED" == "true" ]; then
-    systemctl restart "$SPAMD_SERVICE"
-    echo "SpamAssassin service ($SPAMD_SERVICE) restarted."
+    if [ "$SUBDOMAIN" == "YES" ]; then
+        if ! check_spamassassin_exists "$SPAMASSASSIN_ENTRY_SUB" "$SPAMASSASSIN_FILE"; then
+            add_domain_to_file "$SPAMASSASSIN_ENTRY_SUB" "$SPAMASSASSIN_FILE"
+            echo "Added $SPAMASSASSIN_ENTRY_SUB to $SPAMASSASSIN_FILE."
+            SPAMASSASSIN_CHANGED=true
+        else
+            echo "$SPAMASSASSIN_ENTRY_SUB already exists in $SPAMASSASSIN_FILE."
+        fi
+    fi
+
+    if [ "$SPAMASSASSIN_CHANGED" == "true" ]; then
+        spamassassin_running=$(/usr/local/vesta/bin/v-list-sys-services | grep 'spamassassin\|spamd' | grep -c 'running')
+        if [ $spamassassin_running -eq 1 ]; then
+            echo "== Restarting SpamAssassin"
+            systemctl restart "$SPAMD_SERVICE"
+            if [ $? -eq 0 ]; then
+                echo "SpamAssassin service ($SPAMD_SERVICE) restarted."
+            else
+                echo "Failed to restart SpamAssassin service ($SPAMD_SERVICE)."
+                exit 1
+            fi
+        else
+            echo "WARNING: SpamAssassin service ($SPAMD_SERVICE) is not running."
+            exit 1
+        fi
+    fi
 fi
 
 #----------------------------------------------------------#
diff --git a/bin/v-whitelist-email-account b/bin/v-whitelist-email-account
--- a/bin/v-whitelist-email-account
+++ b/bin/v-whitelist-email-account
@@ -79,37 +79,51 @@ BLACKLIST_ENTRY_SUB="*.$DOMAIN"
 #                SpamAssassin Whitelist                    #
 #----------------------------------------------------------#
 
-echo "Updating $SPAMASSASSIN_FILE..."
+if [ -f "$SPAMASSASSIN_FILE" ]; then
+    echo "Updating $SPAMASSASSIN_FILE..."
 
-# Check if the email address or its domain is already blacklisted
-if check_blacklisted "$EMAIL" "$SPAMASSASSIN_FILE"; then
-    echo "Cannot whitelist $EMAIL. It is already blacklisted."
-    exit 1
-fi
+    # Check if the email address or its domain is already blacklisted
+    if check_blacklisted "$EMAIL" "$SPAMASSASSIN_FILE"; then
+        echo "Cannot whitelist $EMAIL. It is already blacklisted."
+        exit 1
+    fi
 
-if check_blacklisted "$BLACKLIST_ENTRY_MAIN" "$SPAMASSASSIN_FILE"; then
-    echo "Cannot whitelist $EMAIL. The domain $DOMAIN is already blacklisted."
-    exit 1
-fi
+    if check_blacklisted "$BLACKLIST_ENTRY_MAIN" "$SPAMASSASSIN_FILE"; then
+        echo "Cannot whitelist $EMAIL. The domain $DOMAIN is already blacklisted."
+        exit 1
+    fi
 
-if check_blacklisted "$BLACKLIST_ENTRY_SUB" "$SPAMASSASSIN_FILE"; then
-    echo "Cannot whitelist $EMAIL. The subdomain of $DOMAIN is already blacklisted."
-    exit 1
-fi
+    if check_blacklisted "$BLACKLIST_ENTRY_SUB" "$SPAMASSASSIN_FILE"; then
+        echo "Cannot whitelist $EMAIL. The subdomain of $DOMAIN is already blacklisted."
+        exit 1
+    fi
 
-# Add the email to whitelist if not already present
-if ! check_entry_exists "$WHITELIST_ENTRY" "$SPAMASSASSIN_FILE"; then
-    add_entry_to_file "$WHITELIST_ENTRY" "$SPAMASSASSIN_FILE"
-    echo "Added $WHITELIST_ENTRY to $SPAMASSASSIN_FILE."
-    SPAMASSASSIN_CHANGED=true
-else
-    echo "$WHITELIST_ENTRY already exists in $SPAMASSASSIN_FILE."
-fi
+    # Add the email to whitelist if not already present
+    if ! check_entry_exists "$WHITELIST_ENTRY" "$SPAMASSASSIN_FILE"; then
+        add_entry_to_file "$WHITELIST_ENTRY" "$SPAMASSASSIN_FILE"
+        echo "Added $WHITELIST_ENTRY to $SPAMASSASSIN_FILE."
+        SPAMASSASSIN_CHANGED=true
+    else
+        echo "$WHITELIST_ENTRY already exists in $SPAMASSASSIN_FILE."
+    fi
 
-# Restart SpamAssassin only if changes were made
-if [ "$SPAMASSASSIN_CHANGED" == "true" ]; then
-    systemctl restart "$SPAMD_SERVICE"
-    echo "SpamAssassin service ($SPAMD_SERVICE) restarted."
+    # Restart SpamAssassin only if changes were made
+    if [ "$SPAMASSASSIN_CHANGED" == "true" ]; then
+        spamassassin_running=$(/usr/local/vesta/bin/v-list-sys-services | grep 'spamassassin\|spamd' | grep -c 'running')
+        if [ $spamassassin_running -eq 1 ]; then
+            echo "== Restarting SpamAssassin"
+            systemctl restart "$SPAMD_SERVICE"
+            if [ $? -eq 0 ]; then
+                echo "SpamAssassin service ($SPAMD_SERVICE) restarted."
+            else
+                echo "Failed to restart SpamAssassin service ($SPAMD_SERVICE)."
+                exit 1
+            fi
+        else
+            echo "WARNING: SpamAssassin service ($SPAMD_SERVICE) is not running."
+            exit 1
+        fi
+    fi
 fi
 
 #----------------------------------------------------------#
diff --git a/bin/v-whitelist-email-domain b/bin/v-whitelist-email-domain
--- a/bin/v-whitelist-email-domain
+++ b/bin/v-whitelist-email-domain
@@ -78,38 +78,52 @@ BLACKLIST_ENTRY_SUB="*.$DOMAIN"
 #                SpamAssassin Whitelist                    #
 #----------------------------------------------------------#
 
-echo "Updating $SPAMASSASSIN_FILE..."
+if [ -f "$SPAMASSASSIN_FILE" ]; then
+    echo "Updating $SPAMASSASSIN_FILE..."
 
-# Check if the domain is already blacklisted
-if check_blacklist_exists "$DOMAIN" "$SPAMASSASSIN_FILE"; then
-    echo "Cannot whitelist $DOMAIN. It is already blacklisted."
-    exit 1
-fi
+    # Check if the domain is already blacklisted
+    if check_blacklist_exists "$DOMAIN" "$SPAMASSASSIN_FILE"; then
+        echo "Cannot whitelist $DOMAIN. It is already blacklisted."
+        exit 1
+    fi
 
-# Add the main entry
-if ! check_whitelist_exists "$WHITELIST_ENTRY_MAIN" "$SPAMASSASSIN_FILE"; then
-    add_whitelist_to_file "$WHITELIST_ENTRY_MAIN" "$SPAMASSASSIN_FILE"
-    echo "Added whitelist_from $WHITELIST_ENTRY_MAIN to $SPAMASSASSIN_FILE."
-    SPAMASSASSIN_CHANGED=true
-else
-    echo "whitelist_from $WHITELIST_ENTRY_MAIN already exists in $SPAMASSASSIN_FILE."
-fi
-
-# Add the subdomain entry if needed
-if [ "$SUBDOMAIN" == "YES" ]; then
-    if ! check_whitelist_exists "$WHITELIST_ENTRY_SUB" "$SPAMASSASSIN_FILE"; then
-        add_whitelist_to_file "$WHITELIST_ENTRY_SUB" "$SPAMASSASSIN_FILE"
-        echo "Added whitelist_from $WHITELIST_ENTRY_SUB to $SPAMASSASSIN_FILE."
+    # Add the main entry
+    if ! check_whitelist_exists "$WHITELIST_ENTRY_MAIN" "$SPAMASSASSIN_FILE"; then
+        add_whitelist_to_file "$WHITELIST_ENTRY_MAIN" "$SPAMASSASSIN_FILE"
+        echo "Added whitelist_from $WHITELIST_ENTRY_MAIN to $SPAMASSASSIN_FILE."
         SPAMASSASSIN_CHANGED=true
     else
-        echo "whitelist_from $WHITELIST_ENTRY_SUB already exists in $SPAMASSASSIN_FILE."
+        echo "whitelist_from $WHITELIST_ENTRY_MAIN already exists in $SPAMASSASSIN_FILE."
     fi
-fi
 
-# Restart SpamAssassin only if changes were made
-if [ "$SPAMASSASSIN_CHANGED" == "true" ]; then
-    systemctl restart "$SPAMD_SERVICE"
-    echo "SpamAssassin service ($SPAMD_SERVICE) restarted."
+    # Add the subdomain entry if needed
+    if [ "$SUBDOMAIN" == "YES" ]; then
+        if ! check_whitelist_exists "$WHITELIST_ENTRY_SUB" "$SPAMASSASSIN_FILE"; then
+            add_whitelist_to_file "$WHITELIST_ENTRY_SUB" "$SPAMASSASSIN_FILE"
+            echo "Added whitelist_from $WHITELIST_ENTRY_SUB to $SPAMASSASSIN_FILE."
+            SPAMASSASSIN_CHANGED=true
+        else
+            echo "whitelist_from $WHITELIST_ENTRY_SUB already exists in $SPAMASSASSIN_FILE."
+        fi
+    fi
+
+    # Restart SpamAssassin only if changes were made
+    if [ "$SPAMASSASSIN_CHANGED" == "true" ]; then
+        spamassassin_running=$(/usr/local/vesta/bin/v-list-sys-services | grep 'spamassassin\|spamd' | grep -c 'running')
+        if [ $spamassassin_running -eq 1 ]; then
+            echo "== Restarting SpamAssassin"
+            systemctl restart "$SPAMD_SERVICE"
+            if [ $? -eq 0 ]; then
+                echo "SpamAssassin service ($SPAMD_SERVICE) restarted."
+            else
+                echo "Failed to restart SpamAssassin service ($SPAMD_SERVICE)."
+                exit 1
+            fi
+        else
+            echo "WARNING: SpamAssassin service ($SPAMD_SERVICE) is not running."
+            exit 1
+        fi
+    fi
 fi
 
 #----------------------------------------------------------#
